name: e_books
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # LOCAL STORAGE
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator:
  
  # STATE MANAGEMENT
  get:

  # ROUTING
  go_router: ^14.1.4

  # DEPENDENCY INJECTION
  get_it:

  # NETWORKING
  dio:

  # ERROR AND RESULT MANAGEMENT
  dartz:

  # DECORATIONS
  logger:
  flutter_screenutil:
  animated_text_kit:
  mini_music_visualizer:
  avatar_glow:
  super_tooltip:
  cupertino_icons: ^1.0.8
  hexcolor: ^3.0.1
  flutter_svg: ^2.0.10+1
  google_fonts: 6.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # OTHERS
  intl:
  equatable: 
  path_provider: ^2.1.5
  connectivity_plus: ^6.1.4
  freezed_annotation: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  json_serializable: 
  # UNIT TEST
  mockito:
  
flutter:
  assets:
    - assets/animation/
    - assets/images/
    - assets/vectors/
  uses-material-design: true